# Docs: https://circleci.com/docs
version: 2.1

orbs:
  node: circleci/node@2.0.2
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: cimg/base:stable
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Run tests
          command: yarn test --watchAll=false --ci --coverage --reporters=default --reporters=jest-junit --runInBand
      - run:
          name: Run linter
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
      - codecov/upload:
          file: coverage/*.json
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  release:
    docker:
      - image: cimg/node:12.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Compile the code
          command: yarn compile
      - run:
          name: Release
          command: yarn release

  deploy_web:
    docker:
      - image: cimg/node:12.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Build website
          command: yarn build
      # This is necessary to avoid the error related to permissions of Github (see official docs)
      - add_ssh_keys:
          fingerprints:
            - 'd3:31:7b:2f:30:65:1a:a7:43:aa:4a:af:7c:74:87:0e'
      - run:
          name: Deploy website
          command: yarn deploy-web

workflows:
  test_and_release:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["12.16.2", "latest"]
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_web:
          requires:
            - test
          filters:
            branches:
              only: master 
